### PR TITLE
D Wehrle Blog Articles for review and publication

### PR DESCRIPTION
**Pull request by SSpeights**
Hello Martin, 

Pls find two new blog articles for review and, hopefully publication. The Hackathon article was written by Daniel and Anja (designer) on behalf of the Hackathon team and the The Windows Hello Article was written by Daniel. 

It would be great is theses pass muster to merge on Friday or Monday of next week to coincide with the Brown bag day. 

VG, Scott

### CODE REVIEW

**Comment by DonMartin76** [comment]
Hey Scott, could you please straighten up the file names to correspond with the wanted publishing dates? And please also resolve the conflict regarding the `authors.yml` by first merging all changes to the origin repository into your fork.

Thanks, Martin

**Comment by SSpeights** [comment]
K. Got it.

Scott

**Comment by SSpeights** [comment]
Ok I have merged the most current branch of Haufe.dev.io. making a new pull request.

**Comment by DonMartin76** [comment]
I will recline this PR as the content is a little weird. Agreed with @SSpeights that he will re-do it, possibly with a fresh fork.

**Pull request closed without merging**
