### PR TITLE
Notes from CQRS Course

### PR DESCRIPTION
**Pull request by FrederikMichel**

### CODE REVIEW

**Comment by hlgr360** [comment]
Quick review:
- you probably need to add yourself to the author file (check the readme)
- can you add category and tag(s) to your post header

**Comment by FrederikMichel** [comment]
Hi Holger,

I now applied tag and category even though I'm not so sure they match so well cause this post is more about architecture patterns. But I took these for now as I did not want to go overboard with adding categories and tags...

**Comment by DonMartin76** [comment]
The "author" in the post needs to match the author in the `authors.yml`, otherwise the lookup won't work. I.e., it has to read `author: frederik_michel`.

**Comment by FrederikMichel** [comment]
ok, I changed that

**Comment by hlgr360** [comment]
## do you think we should add an additional architecture category?

launchd.io | launchd.de
email: holger@launchd.de
blog: http://hlgr360.wordpress.com
twitter: @hlgr360

Sitz der Gesellschaft: Esslingen | Rechtsform: GbR
Geschäftsführer: Holger Reinhardt & Jonas Dagefoerde
USt-IdNr.: DE288302537

**Comment by FrederikMichel** [comment]
Not a category, but a tag maybe. When I look at the current tags we have I think that a tag called "architecture" covers also "microservice". So either we rename latter one or we have to find another name here. We can also change the category "Conference" to something that also covers trainings so that we do not need another category there

**Comment by hlgr360** [comment]
@FrederikMichel regarding the tags, can you raise an issue against the blog in the issue tracker?

**Pull request merged**
