### PR TITLE
Update authors.yml

### PR DESCRIPTION
**Pull request by EricAtHaufe**
add myself as user.

### CODE REVIEW

**Comment by hlgr360** [comment]
this is just the authors file - did you miss the blog post? or is the blog post a separate pull request?

**Comment by EricAtHaufe** [comment]
Humm,  did misunderstand the text?

“Pull Requests from our design, development and operations teams of Haufe.Group and its subsidiaries are greatly appreciated.  ….”

“Author support was inspired by this blog entryhttps://blog.sorryapp.com/blogging-with-jekyll/2014/02/06/adding-authors-to-your-jekyll-site.html. In order to add information on a new author, edit the_data/authors.yml file, then use the new key as author link in the posts. If an author cannot be found in authors.yml, the content of the author tag will be used verbose. In that case, no links to any social media (Twitter, Github and LinkedIn are currently supported) will be included.”

I just did want  author tab to be in verbose mode.

Best Regards,
Eric

Von: Holger Reinhardt [mailto:notifications@github.com]
Gesendet: Dienstag, 17. Mai 2016 20:54
An: Haufe-Lexware/Haufe-Lexware.github.io Haufe-Lexware.github.io@noreply.github.com
Cc: Schmieder, Eric Eric.Schmieder@haufe-lexware.com; Author author@noreply.github.com
Betreff: Re: [Haufe-Lexware/Haufe-Lexware.github.io] Update authors.yml (#58)

this is just the authors file - did you miss the blog post? or is the blog post a separate pull request?

**Comment by hlgr360** [comment]
But you only edited the authors file without actually adding a blog post?! Usually folks add themselves to the authors file when they submit a blog post for the first time - which is why I was wondering if you forgot to add the blog entry to your pull request or if you are planning to submit one.

**Comment by hlgr360** [comment]
Please add your blog post as well. The authors file is an incentive for folks to add blog posts.

**Comment by EricAtHaufe** [comment]
o.k.  read the instructions and I just want check that I understood everything.

Von: Holger Reinhardt [mailto:notifications@github.com]
Gesendet: Mittwoch, 18. Mai 2016 09:42
An: Haufe-Lexware/Haufe-Lexware.github.io Haufe-Lexware.github.io@noreply.github.com
Cc: Schmieder, Eric Eric.Schmieder@haufe-lexware.com; Author author@noreply.github.com
Betreff: Re: [Haufe-Lexware/Haufe-Lexware.github.io] Update authors.yml (#58)

But you only edited the authors file without actually adding a blog post?! Usually folks add themselves to the authors file when they submit a blog post for the first time - which is why I was wondering if you forgot to add the blog entry to your pull request or if you are planning to submit one.

**Pull request merged**
