### PR TITLE
TEC Day Wrap up

### PR DESCRIPTION
**Pull request by SSpeights**
this is the Summary. Wil add a picture of the meetup as soon as I get one.

### CODE REVIEW

**Comment by marc00s** [comment]
Hey Scott,

thanks for the writeup. 
I would find it useful if we quickly recap what the TecDay is, as this will go to outside readers. Just a short intro what's the format and the intention behind it.
Shouldn't we add some of the other topics as well - a lot of internal colleagues put a lot of effort in and we had great presentations / open talks. Happy to help for myOnboarding, just as one example. We had opentalks about how to bring design and tec together effectively and so on. 

Thnx,
Marco

**Comment by SSpeights** [comment]
Hey Marco, 

Yes, you’re right about re defining what TEC Day is and I will add that to the blog and yes, I will also add some words about the effort that everybody put into the TEC Day - that definitely needs to be recognized. If I am inaccurate about some of the talks in the list then I can change the text.

But for the other talks, I was kind of hoping that everyone would also write their own blog. And that we could add content to the blog for the next 8 weeks or so. Since this is just a summary, I don’t think I could do the talks justice – even if I were to add a paragraph on each one. 

I realize that you are a special case and that you have to wait to see if it’s ok to publish stuff.  Will do this tomorrow. So just hold the merge and I will write it tomorrow first thing.

Vg, Scott

**Comment by SSpeights** [comment]
Ok Added the content that  I think you were talking about.

**Comment by SSpeights** [comment]
pls also one last spelling check.

**Pull request merged**
