### PR TITLE
Building a Highly-Available PostgreSQL Cluster on Azure

### PR DESCRIPTION
**Pull request by sarabadanie**
Hello Holger... 
This is a blog entry to announce the PostgreSQL cluster setup on Azure. 
Thanks,
Esmaeil

### CODE REVIEW

**Comment by hlgr360** [comment]
Can you copy the required header fro another post and adopt it? Otherwise Jenkins will be unhappy ;). You might also want to add yourself as an author in _data/authors.yml

**Comment by hlgr360** [comment]
Can you change the category to 'howto' and add the background image to make it align with the others? Then it is perfect!! :)

**Comment by sarabadanie** [comment]
Apologies if I am too unfamiliar with this blogging concept... hope it is ok now

**Comment by hlgr360** [comment]
Perfect. Thats why I am helping - we all went through it.

**Comment by sarabadanie** [comment]
Thanks. I can see the post online now.

**Pull request merged**
