### PR TITLE
Initial version of my qcon 2016 article

### PR DESCRIPTION
**Pull request by noheadx**
covering cattles-not-pets and the talk from wix.com on microservice journey

### CODE REVIEW

**Comment by DonMartin76** [comment]
Hey Axel; you will need to add the header section, and possibly also your info inside the `authors.yml` file in order to make your blog look like you want. Right now, it doesn't render well. Compare with the other blog posts to see how the post must look like.

Additionally, after the sentence "For WIX.com already this first step of splitting the monolith brought significant benefits:", you will need to add a blank line for the bullet point list to be recognized as such. Right now, it's just rendered as a mess.

**Comment by noheadx** [comment]
Hi Martin, thanks for the feedback, I added the header, myself as an author and fixed the bullet point list.

**Comment by DonMartin76** [comment]
Renders fine now. Care to add a link to www.semigator.de behind the first occurrence of Semigator in your text? Plus perhaps setting the Blog date to March 14th, as we're probably not going to publish it today (but tomorrow, Monday, that is).

**Comment by noheadx** [comment]
link added, changed date in filename

**Comment by hlgr360** [comment]
I will merge the pull first thing tomorrow .. that will hopefully also give it some exposure after today being election day.

**Comment by noheadx** [comment]
thanks! But don't get me started on this day...

**Pull request merged**
