### PR TITLE
ML Lab Summary

### PR DESCRIPTION
**Pull request by SSpeights**
Want to link the video presentation naturally, will do this before or post Friday publication. Comment welcome. S

### CODE REVIEW

**Comment by Kodrafo** [comment]
Hi Scott,

kannst du den Pullrequest gegen den PrepareContent Branch machen? Dann können wir uns das Ganze anschauen bevor wir es live stellen.

VG Rainer

Von: Scott Speights <notifications@github.com>
Gesendet: Mittwoch, 12. September 2018 12:33
An: Haufe-Lexware/Haufe-Lexware.github.io <Haufe-Lexware.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Haufe-Lexware/Haufe-Lexware.github.io] ML Lab Summary (#153)


Want to link the video presentation naturally, will do this before or post Friday publication. Comment welcome. S

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153

Commit Summary

  *   finished editng
  *   added images to repo/article
  *   image

File Changes

  *   A _posts/2018-09-14-mllab_with_aws.md<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-0> (38)
  *   A images/MLLab/Goban.jpg<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-1> (0)
  *   A images/MLLab/MRW.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-2> (0)
  *   A images/MLLab/ProductStation.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-3> (0)
  *   A images/MLLab/ProductStations.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-4> (0)
  *   A images/MLLab/RF.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-5> (0)
  *   A images/MLLab/WMgh.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-6> (0)
  *   A images/MLLab/YY.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-7> (0)
  *   A images/MLLab/highlyengaged.JPG<https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153/files#diff-8> (0)

Patch Links:

  *   https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153.patch
  *   https://github.com/Haufe-Lexware/Haufe-Lexware.github.io/pull/153.diff

**Comment by SSpeights** [comment]
Yes, Ok.

**Comment by SSpeights** [comment]
Sorry can’t see this branch in the dev blog. Is it called pr/120? I didn’t know the dev blog had a “prepare content” actually (or had forgotten).

**Comment by Kodrafo** [comment]
Ah sorry. I’m wrong. PrepareContent does only exist for the techradar.

Regards
Rainer

Von: Scott Speights <notifications@github.com>
Gesendet: Mittwoch, 12. September 2018 12:51
An: Haufe-Lexware/Haufe-Lexware.github.io <Haufe-Lexware.github.io@noreply.github.com>
Cc: Zehnle, Rainer <Rainer.Zehnle@haufe-lexware.com>; Comment <comment@noreply.github.com>
Betreff: Re: [Haufe-Lexware/Haufe-Lexware.github.io] ML Lab Summary (#153)

Sorry can’t see this branch in the dev blog. Is it called pr/120? I didn’t know the dev blog had a “prepare content” actually (or had forgotten).

**Pull request merged**
