### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by SSpeights**
fixed missing word, changed link to "evolve" link, Added a short parenthetical text. Pls merge

### CODE REVIEW

**Comment by hlgr360** [comment]
You have a merge conflict .. can you try to resolve it?

**Comment by SSpeights** [comment]
OK.

**Comment by hlgr360** [comment]
never mind .. I did it
-----
http://www.launchd.de
holger@launchd.de | @hlgr360
http://hlgr360.wordpress.com


Sitz der Gesellschaft: Esslingen | Rechtsform: GbR
Geschäftsführer: Holger Reinhardt & Jonas Dagefoerde
USt-IdNr.: DE288302537

**Comment by SSpeights** [comment]
Ok. thanks.

**Pull request merged**
