### PR TITLE
k8s article

### PR DESCRIPTION
**Pull request by raulfiru**
my first article @hlgr360  ;)

k8s how-to

### CODE REVIEW

**Comment by hlgr360** [comment]
did you update the author file?

**Comment by hlgr360** [comment]
You need to update Haufe-Lexware.github.io/_data/authors.yml

**Comment by raulfiru** [comment]
Nope.. i'll have to do that when i have proper inter et and i'll reply to this

**Comment by DonMartin76** [comment]
You have a few typos in there, like `i` instead of `I`. Would you mind just going over the post and correct those? As an alternative, I can offer to do it post merge on master here.

**Comment by raulfiru** [comment]
done @hlgr360 and done @DonMartin76 (the ones i have seen)

**Pull request merged**
