### PR TITLE
Addendum to Cognito + ADFS how-to article

### PR DESCRIPTION
**Pull request by Dutzu**
Added explanation on how often Cognito refreshes the Federation Metadata and added recommendation for that approach rather than explicitly uploading a metadata file.

### CODE REVIEW

**Review by hlgr360 — CHANGES_REQUESTED** [review]
Can you split this into two separate blog posts .. rename the original one to part 1 and provide a quick summary at the top 'This is the first part of a 2 part series on how to ... ' with the link to part 2 plus a forward link to part 2 at the bottom and add a new blog post for part 2 and provide similar summary on the top but pointing back to part 1.

**Comment by Dutzu** [comment]
It doesn't really make sense to have it split because the information in both parts is so tightly coupled. And the article is already live in the wild and referenced. The things I added were a recommendation that I learnt about shortly after the pull request was merged and now I added some mappings as text so they can be copy & pasted easily by people following the step-by-step tutorial (requested by several colleagues that used the article as a guide already)

**Comment by hlgr360** [comment]
It looked like you have added a second part - or did I misread? It looked more than just a few comments.

**Comment by Dutzu** [comment]
No, it really was just a small addendum to replace a paragraph where I initially said I don't know how something behaves and can't recommend it but later figured it out + adding something that is visible in a screenshot as a markdown table as well to make it easier to copy & paste into your own cognito configuration should you want to follow the tutorial to the letter. 

They are just improvements not really new content

**Review by hlgr360 — APPROVED** [review]

**Pull request merged**
