### PR TITLE
New article: how to automate ami's with packer

### PR DESCRIPTION
**Pull request by danieltiron**

### CODE REVIEW

**Comment by hlgr360** [comment]
umph ... currently the posts are scheduled to go live in 2018 ... the filename denotes the publishing date

**Comment by marc00s** [comment]
thnx, didn't see that.

**Comment by danieltiron** [comment]
Hi Holger! Huh, sorry for this. This can't be solved if the filename is changed?

**Comment by hlgr360** [comment]
hehe .. no problem. Already taken care of. Article is up on the blog

**Comment by danieltiron** [comment]
Thanks!

**Pull request merged**
